### ISSUE TITLE
Implement journal catchup logic

### ISSUE THREAD

**Issue by yusefnapora** [mediachain/mediachain-client#22]
Since clients have direct access to the datastore, putting the blockchain catchup logic into the RPC service puts overhead on that service that can be better pushed into the clients.  

Implementing the catchup in the clients will scale much better, since the rpc service can just send incoming events to all observers without having to manage state per-client, and we can spread the datastore load across all the clients instead of aggregating it in the rpc facade.

The RPC streaming is being refactored now by @vyzo, so we should update this issue once the implementation is finalized.  But the basics are:
- rpc stream will send current (in-progress) block, plus all future journal events as they happen (including publication of new blocks)
- client will check the `chain` pointer of the received block, inspect its local cache (if any), and fetch the block if it's unknown.
- client repeats until it receives a block with a nil chain pointer (genesis block).
- if necessary, the client can fetch the canonical records in each block as part of the process, or it can just do that on demand as necessary, e.g. in response to a user query

It seems like a good idea to have a cache of the blockchain in a local db.  Then we won't need to catchup the chain for each launch, and we won't fall over when the blockchain gets too big to fit into memory.  Using sqlite would avoid an external dependency.  We could just stick the block CBOR into a sqlite blob field, keyed by multihash string representation).  Or there are [rocksdb python bindings](https://github.com/stephan-hof/pyrocksdb) but I don't know if that's worth the dependency.

**Comment by vyzo** [comment]
rocks is pretty well suited as it is a key-value store and we already use it on the servers. 
So it's probably ok to pull it as a dependency.

**Comment by yusefnapora** [comment]
yeah, rocks is probably better suited.  The install instructions for the python bindings have you build the rocksdb shared lib from source, which is a little annoying.  But maybe we could include the built library if we build a python wheel for the client project?  I'm not sure how that works exactly.

**Comment by vyzo** [comment]
Maybe better to implement a package installer that builds from source; I don't like the idea of including binaries.

**Comment by parkan** [comment]
Client should be ok to do as sdist, the indexer has a million dependencies and I'm a bit reluctant to do that same there.
