### ISSUE TITLE
Use grpcio-tools to build

### ISSUE THREAD

**Issue by parkan** [mediachain/mediachain-client#33]
Making end users build the protoc grpc plugin is unreasonable, we should be able to use https://pypi.python.org/pypi/grpcio-tools
- [ ] require pip > 8.1 (can we specify this?)
- [ ] add grpcio-tools dependency
- [ ] use grpcio-tools provided protoc in the build script

**Comment by yusefnapora** [comment]
Now that grpcio-tools has been bumped to 0.15.0, this is so close to being possible.  But there's a bug at the moment that causes an empty `import` line to be generated: https://github.com/grpc/grpc/issues/7101

Once that's fixed and a new release is out, we can stop depending on a source install of grpc to build the protos.

Or if we get impatient, we could just use sed: `sed s/^import $/import grpc/g $file_pb2.py` 😄

**Comment by parkan** [comment]
soooo cloooose

**Comment by parkan** [comment]
Fixed in https://github.com/mediachain/mediachain-client/pull/45
