### ISSUE TITLE
Publish to PyPI

### ISSUE THREAD

**Issue by parkan** [mediachain/mediachain-client#41]
Process looks ok: http://peterdowns.com/posts/first-time-with-pypi.html
- [x] create `.pypirc`
- [x] add `LICENSE` (MIT?)
- [x] add `setup.cfg` to point to `README.md`
- [x] upload to PyPI test
- [ ] upload to PyPI live

**Comment by parkan** [comment]
@yusefnapora you're second in command on this

**Comment by yusefnapora** [comment]
Aye aye, pypi cap'n!
