### ISSUE TITLE
logging api

### ISSUE THREAD

**Issue by yusefnapora** [mediachain/mediachain-client#89]
It would be nice to use the [logging module](https://docs.python.org/2/library/logging.html) so we can spit out debug logs, etc.  I've been sprinkling print statements around and (usually) remembering to take them out before merging in PRs, but some debug info would be good to keep in, hidden behind a flag or environment variable so it doesn't spam normal users.

**Comment by parkan** [comment]
+1, down to blanket replace prints with this
